alwaysontop/alwaysontop.css, alwaysontop/alwaysontop.html, alwaysontop/alwaysontop.js, alwaysontop/render.js
Depends on https://github.com/jitsi/jitsi-meet/pull/2242
=> fix(aot): Handle the use case when the video is not available

alwaysontop/main.js
=> Fixed Typo

alwaysontop/alwaysontop.js, alwaysontop/main.js, alwaysontop/render.js
- minimum size is the starting size of the window
- aspect ratio of video gets preserved on resize, and empty spaces either on top-bottom/left-right are gray background. this is discussed and agreed with PM
=> Make always on top window resizable

package.json, powermonitor/render.js
=> fix(powermonitor): Fix crash due to non-initialized postis channel

powermonitor/main.js
=> fix(powermonitor): Fix condition for sending events

package-lock.json, package.json, screensharing/main.js
=> Fix screen capture permissions lib not being bundled

alwaysontop/render.js
=> [AOT] Fix `focus` listener being removed permanently in a certain scenario

alwaysontop/alwaysontop.css
The  screenshots also contains changes from:
https://github.com/jitsi/jitsi-meet/pull/9090
=> feat(aot): redesign AOT close button

.github/workflows/ci.yml, package-lock.json, package.json
Adds prebuild for electron 13 and fixes
```
In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: error: no member named 'GetContents' in 'v8::ArrayBuffer'
data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
~~~~~~  ^
1 error generated.
make: *** [Release/obj.target/sourceId2Coordinates/node_addons/sourceId2Coordinates/src/index.o] Error 1
```
=> chore(deps): prebuild for electron 13

package-lock.json, package.json, remotecontrol/render.js
Includes prebuilds with stable Node-API ABI.
=> Switch to forked, prebuild robotjs

package-lock.json, package.json
prebuild-install needs to be updated to work correctly with npm8, see
https://github.com/prebuild/prebuild-install/releases/tag/v6.0.0
=> fix: use napi also during normal package install

popupsconfig/main.js, popupsconfig/render.js
It seems that some workarounds related to the Dropbox OAuth are not
needed anymore.
=> fix(popupsconfig): Dropbox cleanup.

alwaysontop/render/index.js
- fix camera preview sometimes showing as a black screen in the bottom left corner when
screen sharing
- fix camera preview sometimes being out of sync with the in-meeting video off/on state
and instead showing a black video when video is off and no video when video is on
=> fix(aot) Fix camera preview becoming unsynced when screen sharing.

.github/workflows/ci.yml, package-lock.json, package.json
Otherwise projects not building for arm64 on macOS (yet) run into a build problem because the prebuild cannot be found.
=> Darwin x64 only

README.md, alwaysontop/main/index.js
Fixes: https://github.com/jitsi/jitsi-meet-electron-sdk/issues/133
=> fix(aot) fix hiding when SS on Windows

.github/workflows/ci.yml, README.md
=> ci: autopublish to npm on every commit

alwaysontop/constants.js, alwaysontop/index.js, alwaysontop/main/index.js, alwaysontop/main/utils.js, alwaysontop/render/index.js, index.js, powermonitor/main.js
@saghul @horymury 
There are 3 commits in this pr for easier review.
=> ref(aot) refactor aot ipc

alwaysontop/render/index.js
Use the renderer logger in the renderer code.
=> fix(aot) fix bogus import

popupsconfig/main.js
See https://www.electronjs.org/docs/latest/breaking-changes#removed-webcontents-new-window-event
=> popupconfig: adjust to new-window event replacement

.github/dependabot.yml
Reduce dependabot to monthly while at it
=> Propose github actions updates via dependabot

remotecontrol/render.js
- caps lock is functional following this change
=> fix(remote-control) Fix pressing caps lock causing crash
