- package-lock.json
- package.json
This dep update brings in the jitsi fork rebased onto commit d870ddb of robotjs. The recent robotjs fixes include support for Electron 5.
> chore(deps): update robotjs fork to d870ddb

- alwaysontop/constants.js
- alwaysontop/main.js
- alwaysontop/render.js
This fixes :
https://github.com/electron/electron/issues/9477
On monitors having scale options applied,window.setPosition() also cause a growth of the window. 
The fix consists in resetting to initial window size once the move/drag event finished.
This only applies on Windows.
> Fix window resize on move

- alwaysontop/main.js
- alwaysontop/render.js
- package-lock.json
- package.json
Fixes cases in which AOT open and close are called in quick succession resulting in white non-controllable AOT window
> JIT-2390 Fix white non-controllable AOT in certain cases

- README.md
- index.js
- package-lock.json
- package.json
- screensharing/constants.js
- screensharing/index.js
- screensharing/main.js
- screensharing/render.js
- screensharing/screenSharingTracker.html
- screensharing/screenSharingTracker.js
Functionality that will create an always on top window in bottom center of the screen whenever the user start a content sharing session.
The purpose is to let the user know he is sharing his screen.
> Add screen sharing tracker window

- package-lock.json
- package.json
- screensharing/constants.js
- screensharing/main.js
- screensharing/screenSharingTracker.html
On Windows we need to specify `-webkit-app-region: no-drag;` for elements of a draggable window in order to interact with them, i.e. the Stop sharing button in our case.
Also from time to time some sort of provisory font is loaded before the css specified one, which caused text shift one line, giving the window more width seems to fix this problem.
> Fix screen-share tracker on Windows 10 OS

- alwaysontop/render.js
@saghul @hristoterezov 
Encountered this bug where the browserwindow was not found based on the id. Added a failsafe mechanism for this case.
> alwaysontop/renderer(fix): Prevent crash on new browser window

- alwaysontop/render.js
- screensharing/main.js
Workaround for electron crashing (strictly a crash, but a failure that ends in the app being forcefully closed) when AoT window is quickly closed and opened during both a focus (main window) and navigate away from the meeting page on Windows.
I would also only hide on dbclick but this breaks current integration as navigating is only one on close.
I also have some performance concerns as the AoT window will still be open and video is piped to it even when it's not visible, I haven't deeply looked into also tackling this potential perf issue.
> Keep AoT window open during meeting: hide & show insetad of close & open

- powermonitor/main.js
A fix for a bug, which occurs after closing the jitsi window on Mac osx:
Also used the variable `browserWindow` instead of `jitsiMeetWindow` - seems more consistent.
> Fix for missing browserWindow after closing the windows on osx

- alwaysontop/render.js
After AoT is closed, calling win methods (e.g. hide) throw exceptions even the isDestroyed method returns false.
> Fix AoT close race condition

- alwaysontop/main.js
- alwaysontop/render.js
- package-lock.json
- package.json
@andreieftimie After merging https://github.com/jitsi/jitsi-meet-electron-utils/pull/72 I realised that actually we have broken the will-close event. This PR brings back the original behaviour of the event. Since it is abstract event I'm triggering it for the use cases when we hide the AOT. In addition I realised that this would probably solve the issue you described for the double click. That's why I also changed the double click to hide AOT instead of close it.
Could you please verify that this will work for your use case?
> fix(AOT): will close event.

- alwaysontop/main.js
This solves AOT rendering above full-screen applications (on windows Remote Desktop Connection for example) which allow users in a meeting to open a RDP connection and still see the meeting AOT window above it (especially important if the user has a single screen).
See a lengthy in-depth discussion here https://github.com/electron/electron/issues/10078
> Use AOT window layering to allow it to render above full screen apps

- package-lock.json
- package.json
- screensharing/main.js
Context isolation must be disabled, until we support it properly.
> Fix screen-sharing tracker on Electron 12

- package-lock.json
- package.json
The new version uses a new API in  macOS Big Sur which allows to check
if the permission was grante without prompting.
The module is now a Node addon which makes universal builds possible.
The commit we are uppdating to is in PR:
https://github.com/karaggeorge/mac-screen-capture-permissions/pull/8
> feat(deps) uppdate mac-screen-capture-permissions

- package-lock.json
- package.json
karaggeorge/mac-screen-capture-permissions#8 was merged and released as 2.0.0,
so switch back to released upstream version.
> feat(deps) update mac-screen-capture-permissions

- node_addons/sourceId2Coordinates/src/index.cc
Fixes deprecation warning as all modules have to be context-aware for
electron 14+
See https://github.com/electron/electron/issues/18397
Signed-off-by: Christoph Settgast <csett86@web.de>
> fix(remotecontrol): make native module context-aware

- package-lock.json
- package.json
- screensharing/constants.js
Will be reverted as soon as https://github.com/octalmage/robotjs/pull/696
is merged upstream.
> remotecontrol: Move to context-aware robotjs fork for electron 14+

- .github/workflows/ci.yml
Requires npm access token in secret `NPM_TOKEN`
Closes #144
> ci: publish release to npm

- package.json
Not critical, as github is doing redirects, just cleanup
> fixup repository url in package.json

- .github/workflows/ci.yml
- README.md
- binding.gyp
- node_addons/sourceId2Coordinates/index.js
- package-lock.json
- package.json
- test/sourceId2Coordinates.test.js
bundles the prebuilds in the npm package, saving extra downloads and
recommended by prebuild maintainers.
> Switch to prebuildify

- package-lock.json
- package.json
node-abi was introduced to get prebuilds with "prebuild" with
current electron versions. "prebuild" is replaced with "prebuildify",
thus node-abi is no longer used.
> cleanup: remove unused node-abi

- alwaysontop/constants.js
- alwaysontop/main/index.js
- alwaysontop/render/index.js
- Now focus handler also checks whether the meeting is intersecting before hiding AOT
- Now on conference left we do not remove the listeners because it not always means that meeting ended.
This fixes cases when we have a passcode/lobby and also breakout rooms when conferenceLeft and joined are called
during the same meeting session.
> fix(aot) Fix intersection; fix conference left

- screensharing/constants.js
- screensharing/main.js
- screensharing/render.js
Starting with electron 17, desktopCapturer.getSources(options) is
only available on the main process, not the renderer.
See https://www.electronjs.org/docs/latest/breaking-changes#removed-desktopcapturergetsources-in-the-renderer
> fix(screenshare): adapt to electron 17+ desktopCapturer.getSources

- alwaysontop/main/index.js
This fixes an issue where in case the main window handles the `close` event and does preventDefault() so it dismisses the close, AOT window will close, which causes 2 issues:
-  AOT will not show up anymore for the ongoing meeting
-  when the meeting ends, the `_onConferenceLeft` from renderer will try to close AOT window again, but will crash since AOT is already closed.
> fix(aot) Remove main window close handler

- screensharing/main.js
- screensharing/preload.js
- screensharing/screenSharingTracker.js
- Enable context isolation for this window
- Add a preload script
- Disable unnecessary Node integration
- Sanitize query parameter handling
> fix(ScreenSharingTracker) use a preload script

- .github/workflows/ci.yml
- README.md
- binding.gyp
- install.js
- package.json
- remotecontrol/main.js
- test/sourceId2Coordinates.test.js
the native code anyway only is required and supports windows
> refactor: guard and build native code only on windows

- .github/workflows/ci.yml
actions/setup-node was interfering and not necessary with the autopublisher action
> fix(ci): publish to npm

- .github/workflows/ci.yml
jitsi/gh-action-autopublish does not work, as it tries to do npm install,
which will fail due to binary dependencies (robotjs) in the docker
container of jitsi/gh-action-autopublish
> fix(ci): autopublish v2

- package-lock.json
- package.json
Reverts 818cd55feb3bcdead9e8128cc3b9d6aaf527fb39
See compile failures as prebuilds on windows are no longer used
eg. here https://github.com/jitsi/jitsi-meet-electron/runs/7639735746?check_suite_focus=true
> fix: downgrade node-gyp-build

- alwaysontop/render/index.js
the videoConferenceLeft handler cause the window to be wrongfully disposed when triggered due to password required
> fix(aot) remove unnecessary handlers

- .husky/pre-push
- package-lock.json
- package.json
The auto-release bot should still work since it doesn't install the
pre-commit hook.
Sample run:
```
$ git push --dry-run 
You can't commit directly to master branch
husky - pre-push hook exited with code 1 (error)
error: failed to push some refs to 'github.com:jitsi/jitsi-meet-electron-utils.git'
```
> chore(build) prevent accidental pushes to master

- README.md
- package.json
Avoid the prepare step, which also runs when publishing.
> fix(build): Disable autoinstall and document husky instead 

- remotecontrol/render.js
This is in order to avoid 
on Electron apps using electron v23.0.0 and newer
> fix(remote-control) Move robotjs import

- screensharing/render.js
We may fail to access the iframe's contentWindow, but we can ignore that since the new hook doesn't require it.
Fixes: https://github.com/jitsi/jitsi-meet-electron-sdk/issues/368
Fixes: https://github.com/jitsi/jitsi-meet-electron-sdk/issues/325
> fix(screen-sharing) fix depredcated ss hook

- alwaysontop/render/index.js
- was able to reproduce on Windows only
- was reproducible with Jitsi Electron app and another jitsi-based app
- error: window.open blocked due to active file chooser. when AOT tries to open (window.open) while the open file dialog is shown
> fix(aot) Fix crash on open AOT when a file choose dialog is opened

- .github/workflows/ci.yml
- install.js
the upload action no longer allows "appending" to the same name, so merge on download as described https://github.com/actions/download-artifact?tab=readme-ov-file#download-multiple-filtered-artifacts-to-the-same-directory
> ci: update to v4 actions

- .github/workflows/ci.yml
- package-lock.json
- package.json
Required because of https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2
> deps: bump node-gyp-build to build on windows
